config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'account', to: 'devise/sessions#show'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'messages', to: 'static_pages#messages'
  get 'love-what-you-do', to: 'static_pages#love-what-you-do'
  get 'buy-the-book', to: 'static_pages#buy-the-book'
  get 'past-events', to: 'static_pages#past-events'
  get 'press', to: 'static_pages#press'
  get 'heart', to: 'static_pages#heart'
  get 'press-form', to: 'static_pages#press-form'

  get '/fabrik_book', to: 'links#fabrik_book'
  get '/amazon_book', to: 'links#amazon_book'
  get '/fb', to: 'links#fb'
  get '/insta', to: 'links#insta'
  get '/asher', to: 'links#asher'
  get '/ff', to: 'links#ff'
  get '/fab', to: 'links#fab'
  get '/twitter', to: 'links#twitter'


  # resources :articles do 
  #   member do
  #     delete :delete_image_attachment
  #   end
  # end
  # get 'press', to: 'articles#index', as: 'press'

  # resources :archives do 
  #   member do
  #     delete :delete_image_attachment
  #   end
  # end
  # get 'past-events', to: 'archives#index', as: 'past-events'

  resources :requests, :except => [:new]
  get '/speaking', to: 'requests#new', as: 'speaking'
  post '/speaking', to: 'requests#create'

  resources :features, :except => [:new]
  get '/feature-dana', to: 'features#new', as: 'feature-dana'
  post '/feature-dana', to: 'features#create'

  resources :events do 
    member do
      delete :delete_image_attachment
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_book-options.html.erb
<div class="option o1">
	<%= link_to fabrik_book_path, class: 'ds-link', target: '_blank' do %>
		Buy on fabrikstyle.com
	<% end %>
</div>

<div class="option o2">
	<%= link_to amazon_book_path, class: 'ds-link', target: '_blank' do %>
		Buy on amazon.com
	<% end %>
</div>

app/views/static_pages/about.html.erb
<% @page_title = "About Dana" %>
<% @page_description = "Learn more about Dana Spinola, and how she became a leader in the worlds of fashion, business, and philanthropy." %>

<h1><span>XOXO</span>, Dana</h1>
<div class="ab-sec bio">
	<div class="inside">
		<div class="text">
			<h3 class="as-title"><span class="norm">fab’rik</span> Founder & CVO</h3>
			<p>Born and raised by entrepreneurs, fab’rik Founder Dana Spinola has been taught from a young age that if you love what you do you will never work another day in your life. This mantra inspired her to leave Corporate America and open her first boutique in 2002. Since then, she has carried out her mission of High Style With Heart nationwide with over 40 locations and growing. As Chief Visionary Officer, Dana’s vision for her company is to make women feel beautiful inside and out, one piece of fabric at a time.</p>
		</div>

		<div class="image">
			<%= image_tag('dana-bio1.jpg', alt: "fab'rik founder, Dana Spinola, posing in her office", class: 'img-responsive') %>
		</div>
	</div>
</div>

<div class="ab-sec rec">
	<div class="inside">
		<div class="text">
			<h3 class="as-title">Author &amp; Speaker</h3>
			<p>Forbes called her “one of the five great American Entrepreneurs you haven’t heard of yet but should know” because of her dedication to not only building a growing fashion brand but for inspiring a culture of people to weave purpose into their companies and their life. Dana has taken this message not only onto the pages of her book, love what you do, but to stages across the country. She has been voted Business Person of the Year, Women Making a Mark, and has appeared in dozens of publications from Wall Street Journal to Elle.</p>
		</div>

		<div class="image">
			<%= image_tag('dana-bio7.jpg', alt: "Dana Spinola speaking at a fashion show", class: 'img-responsive') %>
		</div>
	</div>
</div>


<div class="ab-sec philanth">
	<div class="inside">
		<div class="text">
			<h3 class="as-title">Philanthropist</h3>
			<p>Dana has always believed that clothing has the ability to change lives. In 2009, she launched the brand's nonprofit, free fab’rik, which provides free shopping sprees for women in need. Each week the team and a group of volunteers bring racks of clothing into safe houses so the ladies can experience the thrill of boutique shopping, without the pressure of price tags. Dana’s mission is to remind them they are clothed in strength and dignity and can laugh without fear of the future. In 2011 Dana launched fab’rik’s in house clothing line, Asher, named after her daughter. While designing a clothing line has been one of her passions, the purpose behind the line is the real driving force. Proceeds of the line support the adoption process for children in Africa. Each store that carries Asher is matched with an Asher Baby to pray for, share their story and fund their needs until they find a forever home.</p>
			<%= link_to(image_tag('asher-lt.png', class: 'img-responsive logo inline ash', alt: 'Asher Collection logo'), asher_path, target: '_blank', class: 'logo-link') %>
			<%= link_to(image_tag('free-fabrik.png', class: 'img-responsive logo inline free', alt: "free fab'rik logo" ), ff_path, target: '_blank', class: 'logo-link') %>
		</div>

		<div class="image">
			<%= image_tag('africa.jpg', alt: "Dana Spinola with the Asher babies in Africa", class: 'img-responsive') %>
		</div>
	</div>
</div>

<div class="ab-sec message">
	<div class="inside">
		<div class="text">
			<h3 class="as-title">Mom &amp; Household CEO</h3>
			<p>While Dana sits at the head of a leading fashion franchise as well as a non-profit organization, her most rewarding job is being a wife and mom to her four children, two dogs and 20 chickens! She has three wild and adventurous boys, and a strong, fearless daughter, Asher, who they adopted from Ethiopia. When she is not busy speaking or running her company, she loves dance parties with her kids and sushi date nights with her husband. She learned the love of God on a trip to Haiti after the devastating earthquake and has been on a mission to share His love ever since. Her mission is to remind those people with broken dreams to dream big again… and has built her life around that.</p>
		</div>

		<div class="image">
			<%= image_tag('family.jpg', alt: "Dana Spinola and family at her book launch", class: 'img-responsive') %>
		</div>
	</div>
</div>

app/views/static_pages/heart.html.erb
<% @page_title = "Heart" %>
<% @page_description = "Dana Spinola shares her passions, and what started her love of high style with heart." %>

<div class="inside"><div class="title">
	<h1>High style with <span class="lspace">heart.</span></h1>
</div></div>

<div class="boxes">
		<div class="inside">
			<div class="fabrik">
				<div class="text">
					<%= image_tag('fabrik.png', alt: "fab'rik logo", class: 'img-responsive logo fab') %>
					<div class="clearfix"></div>
					<p>
						“While fab’rik was born from a broken heart, it ended up being the thing that made my heart beat”. In 2001 after a break up with a long-term boyfriend, Dana asked herself the question, ‘what is my dream job’ then decided to chase it. After a year of writing a business plan, 14 banks saying no to a loan and a break in her first day of business, Dana opened her first boutique. With a mission to create a place where everyone could afford to feel beautiful, her concept was high style but without the high price tags. Her first store in Atlanta, GA soon became the go to spot to purchase your most complimented outfit and she realized she needed to grow that concept. She started franchising to allow other like-minded, big-hearted businesswomen to own their own fab’rik. Now with 40 locations and growing, fab’rik is well on its way to a becoming a household brand known for High Style with Heart. 
					</p>

					<%= link_to "Shop fab'rik", fab_path, target: '_blank', class: 'ds-link' %>
					<%= link_to "Own a fab'rik Store", 'https://fabrikstyle.com/pages/own-a-store', target: '_blank', class: 'ds-link alt' %>
				</div>

				<div class="image">
					<%= image_tag('heart-fabx.png', alt: "fab'rik boutique store front", class: 'img-responsive') %>
				</div>
			</div>
			
			<div class="border-row"></div>

			<div class="freefab">
				<div class="text">
					<%= image_tag('free-fabrik.png', alt: "free fab'rik logo", class: 'img-responsive logo') %>
					<p>free fab'rik is a non-profit that hosts free shopping sprees for young ladies in need. Founded in 2009 by Dana Spinola, the mission is to restore strength, dignity, and hope to women who have lost theirs as a result of the terrible world of sex trafficking. We host weekly free shopping sprees at safe houses so the ladies can experience the thrill of boutique shopping, without the pressure of price tags. Women from all over volunteer to shop, pray and spend time getting to know these brave women’s stories. The goal is to remind them just how beautiful they are, and cheer them on as they embark on the next phase of their life. We end each spree with a fashion show and the runway is full of confidence and hope! All of our fab’rik locations have clothing bins where you can donate your gently loved clothing or come volunteer with us, it will be a night you won’t forget! </p>
					<%= link_to "Donate to free fab'rik", "http://www.freefabrik.org/donate/", target: '_blank', class: 'ds-link' %>
					<%= link_to "Learn More about free fab'rik", ff_path, target: '_blank', class: 'ds-link alt' %>
				</div>

				<div class="image"><%= image_tag('heart-ffx.jpg', alt: "Clothing rack from free fab'rik event", class: 'img-responsive') %></div>
			</div>
			
			<div class="border-row"></div>

			<div class="asher">
				<div class="text">
					<%= image_tag('asher.png', alt: 'Asher Collection logo', class: 'img-responsive logo ash') %>
					<p>
						Asher is our in house designed clothing line and is the epitome of the fab’rik it girl style, effortless chic. While the designs are beautiful, the reason we design this collection is even more beautiful. On average, hundreds of babies are abandoned by their mothers each month in African hospitals, clinics, police stations and even outdoors and that breaks our heart. Proceeds from every Asher purchase help provide a loving home, basic needs, healthcare and educational fees for African children who have been abandoned. Each store that carries Asher is matched with an Asher Baby to pray for, share their story and fund their needs until they find a forever home. Over 50 of our Asher Babies now have forever homes and the numbers keep growing thanks to all of our customers loving the line!</p>

					<%= link_to "Meet the Asher Babies", 'https://shopasher.com/blogs/asher-babies', target: '_blank', class: 'ds-link' %>
					<%= link_to "Shop Asher Collection", 'https://fabrikstyle.com/collections/asher-collection', target: '_blank', class: 'ds-link alt' %>
				</div>

				<div class="image">
					<%= image_tag('asher-sec.png', alt: 'Dana Spinola and daughter, Asher', class: 'img-responsive') %>
				</div>
			</div>
		</div>
	</div>

app/views/static_pages/home.html.erb
<% @page_title = "Love What You Do" %>
<% @page_description = "Dana Spinola is a business woman, motivational speaker, philanthropist and mother who wants to help you create a life on fire. Dana’s message inspires groups to dream big and live life with meaning." %>
 
<div class="full open">
	<div class="inside lg"> 
		<%= image_tag('dana-hero.jpg', class: 'img-responsive', alt: "Dana Spinola, sitting on her desk in the fab'rik corporate office") %>
	</div>
</div>

<div class="color-text">
	<div class="inside med2-def">
		<h1 class="full-h1">
			<span class="color">Ignite your <span class="fancy">passion.</span></span><br class="mobile">
			<span class="color">Find your <span class="fancy">purpose.</span></span><br>
			<span class="color"> Live life with <span class="fancy">meaning.</span></span></h1>
		<!-- <h1 class="mobile-h1"><span>Ignite your passion.</span><br> <span>Find your purpose.</span><br><span> Live life with meaning.</span></h1> -->
	</div>
</div>

<div class="laysec2">
	<div class="inside lg">
		<%= link_to love_what_you_do_path, class: 'box two' do %>
			<%= image_tag('home-stack.jpg', class: 'img-responsive img-bg', alt: 'Dana Spinola, speaking to a crowd at her book launch'  ) %> 
			<h4>About <span class="norm">love what you do.</span></h4>
			<p>Are you ready to love what you do? This book is your guide to creating a life on fire filled with passion and purpose. Click here to get your hands on a copy and start the love what you do journey for yourself or with your team.  </p>
		<% end %>

		<%= link_to speaking_path, class: 'box one' do %>
			<%= image_tag('home-link2.jpg', class: 'img-responsive img-bg', alt: "Dana Spinola's book, love what you do.") %>  
			<h4>Speaking Engagements</h4>
			<p>From Keynote speeches at your conference, to fireside chats with your team, Dana’s message inspires groups to dream big and live life with meaning. Click here to look at past events and book Dana for your next event.</p>
		<% end %>
	</div>
</div>

<div class="insta">
	<div class="inside lg">
		<div class="tbox">
			<h4>Follow Me On Instagram</h4>
			<h5>@danaspinola</h5>
		</div>

		<script src="http://cdn.lightwidget.com/widgets/lightwidget.js"></script>
		<!-- LightWidget WIDGET sm space -->
		<!-- <iframe src="//lightwidget.com/widgets/31d1a20b17315de4a36bb121b8048ac6.html" scrolling="no" allowtransparency="true" class="lightwidget-widget" style="width:100%;border:0;overflow:hidden;"></iframe> -->

		<!-- LightWidget WIDGET lg space-->
		<iframe src="//lightwidget.com/widgets/df568c51ac3f52d684ae4b8aacd74053.html" scrolling="no" allowtransparency="true" class="lightwidget-widget" style="border:0;overflow:hidden;"></iframe>

	</div>
</div>

app/views/static_pages/press-form.html.erb
<% @page_title = "Feature Dana" %>
<% @page_description = "" %>


<div class="inside med2-def">
	<p>This will be the press form on Monday.</p>
	name 
	email
	phone
	organization
	website
	press deadline
	feature type
	(dd) in person, phone, email
	feature details

</div>

app/views/static_pages/press.html.erb
<% @page_title = "Press" %>
<% @page_description = "Take a look at some of the Dana Spinola's article coverage." %>

<div class="event-lay press">
	<div class="inside med2-def">
		<div class="title"><h1><span>Haute</span> off the Press.</h1></div>
		<div class="btn-side">
			<%= link_to "Feature Dana", feature_dana_path, class: 'ds-link' %>
		</div>
	</div>

	<div class="event-list">
		<div class="inside med-def">
      
			<%# link & img %>
      <%# 07.21.20%20DANA%2015.jpg %>
      <div class="event-li article">
		  	<%= image_tag('', class: 'img-responsive', alt: "The Atlantan's September Editorial Women's Feature") %>
        <div class="textbox">
          <p class="pub">The Atlantan</p>
          <h4>The Atlantan's September Editorial Women's Feature</h4>
          <p class="desc">Making a statement means... not being afraid to put in action what is in your heart. Dana Spinola truly believes that if you do what you love, you'll never work a day in your life.</p>
          <%# <a class="text-link" target="_blank" href="">View Article</a> %>
        </div>
      </div>     

			<%# link & img %>
      <%# 12.05%20DANA'S%20BOOK%2066.jpg %>
      <div class="event-li article">
		  	<%= image_tag('', class: 'img-responsive', alt: "How Women Can Ditch the Guilt When Juggling Careers and Family") %>
        <div class="textbox">
          <p class="pub">Wall Street Journal</p>
          <h4>How Women Can Ditch the Guilt When Juggling Careers and Family</h4>
          <p class="desc">In a new book, “Power Moms,” mothers who reached the top of the corporate ladder explain why feeling guilty over work and family is both futile and a waste of energy.</p>
          <%# <a class="text-link" target="_blank" href="">View Article</a> %>
        </div>
      </div>

      <div class="event-li article">
        <%= image_tag('press-forbes1.jpg', class: 'img-responsive', alt: "Dana Spinola in her office - link to Forbes' Five Great American Entreprenuers") %>
        <div class="textbox">
          <p class="pub">Forbes</p>
          <h4>Five Great American Entreprenuers</h4>
          <p class="desc">Five Great American Entrepreneurs You Haven't Yet Heard Of But Should Know</p>
          <a class="text-link" target="_blank" href="https://www.forbes.com/sites/robertreiss/2018/01/16/five-great-american-entrepreneurs-you-havent-yet-heard-of-but-should-know/#ce825a755d71">View Article</a>
        </div>
      </div>

      <div class="event-li article">
        <%= image_tag('press-atlCo.jpg', class: 'img-responsive', alt: "Love What You Do author Dana Spinola") %>
        <div class="textbox">
          <p class="pub">atl&amp;co</p>
          <h4>"Love What You Do" author Dana Spinola</h4>
          <p class="desc">Fabrik boutique owner Dana Spinola talks about her empowering new book "Love What You Do"</p>
          <a class="text-link" target="_blank" href="https://www.11alive.com/video/entertainment/television/programs/atlanta-and-company/love-what-you-do-author-dana-spinola/85-698bffac-4909-4fe9-853e-52b1a4f0fbda">View Article</a>
        </div>
      </div>

			<%# link & img(?) %>
      <div class="event-li article">
        <%= image_tag('press-rebuild.png', class: 'img-responsive', alt: "Let's Rebuild Together") %>
        <div class="textbox">
          <p class="pub">Atlanta Apparel</p>
          <h4>Let's Rebuild Together</h4>
          <p class="desc">Sharing inspiration and helpful business insider tips from fab'rik CEO and Founder, Dana Spinola, on @atlantaapparel's Instagram.</p>
          <%# <a class="text-link" target="_blank" href="">View Video</a> %>
        </div>
      </div>

			<%# link & img %>
			<%# Screen%20Shot%202021-03-23%20at%2012.26.54%20PM.png %>
      <div class="event-li article">
        <%= image_tag('', class: 'img-responsive', alt: "free fab'rik DREAM. Boutique Launch") %>
        <div class="textbox">
          <p class="pub">free fab'rik</p>
          <h4>free fab'rik DREAM. Boutique Launch</h4>
          <p class="desc">Watch our first ever Dream Boutique Launch at House of Cherith!</p>
          <%# <a class="text-link" target="_blank" href="">View Video</a> %>
        </div>
      </div>

      <div class="event-li article">
        <%= image_tag('press-asbn.png', class: 'img-responsive', alt: "Fab’rik: How Dana Spinola Built a Fashion Empire Fueled By Passion and Purpose") %>
        <div class="textbox">
          <p class="pub">ASBN</p>
          <h4>Fab’rik: How Dana Spinola Built a Fashion Empire Fueled By Passion and Purpose</h4>
          <p class="desc">On today’s show, we take a look at Bridget Fitzpatrick’s conversation with Dana Spinola, Founder, and CEO of Fab’rik.</p>
          <a class="text-link" target="_blank" href="https://www.myasbn.com/small-business-shows/atlanta-small-business-show/fabrik-how-dana-spinola-built-a-fashion-empire-fueled-by-passion-and-purpose/">View Article</a>
        </div>
      </div>

      <div class="event-li article">
        <%= image_tag('press-uw.jpg', class: 'img-responsive', alt: "Spring Symposium 2019") %>
        <div class="textbox">
          <p class="pub">United Way</p>
          <h4>Spring Symposium 2019</h4>
          <a class="text-link" target="_blank" href="https://www.ourunitedway.org/spring-symposium-2019">View Article</a>
        </div>
      </div>
      <div class="clearfix"></div>

      <div class="event-li article">
        <%= image_tag('press-fearless.jpg', class: 'img-responsive', alt: "2019 Fearless Women Campaign – Dana Spinola") %>
        <div class="textbox">
          <p class="pub">Vibe Fitness</p>
          <h4>2019 Fearless Women Campaign – Dana Spinola</h4>
          <a class="text-link" target="_blank" href="https://www.experiencevibefitness.com/vibe/fearless-women/">View Article</a>
        </div>
      </div>
      
      <div class="event-li article">
        <%= image_tag('press-main3.jpg', class: 'img-responsive', alt: "Act Two: Write a Book") %>
        <div class="textbox">
          <p class="pub">Simply Buckhead</p>
          <h4>Act Two: Write a Book</h4>
          <p class="desc">Clothing boutique founder Dana Spinola adds author to her resume</p>
          <a class="text-link" target="_blank" href="https://simplybuckhead.com/act-two-write-a-book/">View Article</a>
        </div>
      </div>
      
      <div class="event-li article">
        <%= image_tag('press-thrill.png', class: 'img-responsive', alt: "Choose Thrilling, Atlanta") %>
        <div class="textbox">
          <p class="pub">The Atlantan</p>
          <h4>Choose Thrilling, Atlanta</h4>
          <p class="desc">Dana Spinola, owner and founder of fab’rik, knows what it means to choose thrilling</p>
          <a class="text-link" target="_blank" href="https://atlantanmagazine.com/porsche-macan-atlanta">View Article</a>
        </div>
      </div>
      
      <div class="event-li article">
        <%= image_tag('press-cnn9.jpg', class: 'img-responsive', alt: "The Power of an Outfit") %>
        <div class="textbox">
          <p class="pub">CNN</p>
          <h4>The Power of an Outfit
          </h4>
          <p class="desc">Atlanta boutique owner invites girls in need into her boutique for free shopping sprees</p>
          <a class="text-link" target="_blank" href="https://www.cnn.com/videos/living/2011/09/23/nr-free-fabrik.cnn">View Video</a>
        </div>
      </div>
      
      <div class="event-li article">
        <%= image_tag('press-cnnSpec2.png', class: 'img-responsive', alt: "How sexual abuse survivors are finding strength and dignity through fashion") %>
        <div class="textbox">
          <p class="pub">CNN</p>
          <h4>How sexual abuse survivors are finding strength and dignity through fashion</h4>
          <a class="text-link" target="_blank" href="https://www.cnn.com/2019/06/06/us/iyw-free-fabrik-abuse-survivors-fashion-trnd/index.html">View Article</a>
        </div>
      </div>
      
      <div class="event-li article">
        <%= image_tag('press-ef1.png', class: 'img-responsive', alt: "Top 500 Franchises") %>
        <div class="textbox">
          <p class="pub">Entreprenuer Magazine</p>
          <h4>Top 500 Franchises</h4>
          <p class="desc">fab'rik named Top 500 Franchises</p>
          <a class="text-link" target="_blank" href="https://www.entrepreneur.com/franchises/fabrik/334105">View Article</a>
        </div>
      </div>
      <div class="clearfix"></div>
      
      <div class="event-li article">
        <%= image_tag('press-ajcx.jpg', class: 'img-responsive', alt: "The fab'rik of Life") %>
        <div class="textbox">
          <p class="pub">AJC</p>
          <h4>The fab'rik of Life</h4>
          <p class="desc">The pitfalls of having it all and the power of living in the now</p>
          <a class="text-link" target="_blank" href="http://specials.myajc.com/fabrik/">View Article</a>
          <a class="text-link dub" target="_blank" href="https://www.youtube.com/watch?v=Mh74JATSLD0">View Video</a>
        </div>
      </div>
      
      <div class="event-li article">
        <%= image_tag('press-huff.jpg', class: 'img-responsive', alt: "Paradigm Shifter") %>
        <div class="textbox">
          <p class="pub">Huffington Post</p>
          <h4>Paradigm Shifter</h4>
          <p class="desc">Dana Spinola shares the essence of fab'rik</p>
          <a class="text-link" target="_blank" href="https://www.huffingtonpost.com/renata-m-black/dana-spinola--the-essence_b_10324046.html">View Article</a>
        </div>
      </div>
      
      <div class="event-li article">
        <%= image_tag('press-forbesx.jpg', class: 'img-responsive', alt: "Fashion Fighting Sex Trafficking") %>
        <div class="textbox">
          <p class="pub">Forbes</p>
          <h4>Fashion Fighting Sex Trafficking
          </h4>
          <p class="desc">How One Atlanta Boutique Is Using Fashion To Help Survivors Of Sex Trafficking</p>
          <a class="text-link" target="_blank" href="https://www.forbes.com/sites/toriutley/2018/01/30/how-one-atlanta-boutique-is-using-fashion-to-help-survivors-of-sex-trafficking/#173d2a1c4c2b">View Article</a>
        </div>
      </div>
      
      <div class="event-li article">
        <%= image_tag('press-chr.jpg', class: 'img-responsive', alt: "Business Person of the Year") %>
        <div class="textbox">
          <p class="pub">Atlanta Business Chronicle</p>
          <h4>Business Person of the Year</h4>
          <p class="desc">Fab'rik founder wins with the wow factor</p>
          <a class="text-link" target="_blank" href="https://www.bizjournals.com/bizwomen/news/profiles-strategies/2017/10/fabrik-founder-wins-with-the-wow-factor.html?page=all">View Article</a>
        </div>
      </div>
      <div class="clearfix"></div>
  
		  <%# %>
      <div class="event-li article">
        <%= image_tag('ml-jez.png', class: 'img-responsive', alt: "Wonder Woman") %>
        <div class="textbox">
          <p class="pub">Modern Luxury</p>
          <h4>Wonder Woman</h4>
          <p class="desc">fab'rik's FAB leading lady</p>
          <a class="text-link" target="_blank" href="https://digital.modernluxury.com/publication/?i=522504&amp;ver=html5&amp;p=60">View Article</a>
        </div>
      </div>
      
      <%# %>
      <div class="event-li article">
        <%= image_tag('press-angelos.jpg', class: 'img-responsive', alt: "Dana Spinola shares why she changed her focus") %>
        <div class="textbox">
          <p class="pub">The Angelos</p>
          <p class="desc">As an entrepreneur, wife, and mother of four, Dana shares her perspective and why she changed her focus and learned to live by the phrase, "You can do anything, just not everything.</p>
          <a class="text-link" target="_blank" href="https://mydigitalpublication.com/publication/?i=574401">View Article</a>
        </div>
      </div>
      <div class="clearfix"></div>
      
      <div class="event-li article">
        <%= image_tag('press-skypointe.jpg', class: 'img-responsive', alt: "Keeping Atlanta Fly") %>
        <div class="textbox">
          <p class="pub">Skypointe Magazine</p>
          <h4>Keeping Atlanta Fly</h4>
          <p class="desc">The Top Atlanta Influencers that keep the City Fly</p>
          <a class="text-link" target="_blank" href="https://www.atl.com/skypointemagazine/">View Article</a>
        </div>
      </div>
      
      <%# %>
      <div class="event-li article">
        <%= image_tag('press-atl.jpg', class: 'img-responsive', alt: "Biz Whiz") %>
        <div class="textbox">
          <p class="pub">Atlanta Magazine</p>
          <h4>Biz Whiz</h4>
          <p class="desc">This business woman continues to find new ways to give back</p>
          <a class="text-link" target="_blank" href="https://digital.modernluxury.com/publication/?i=462307&amp;ver=html5&amp;p=34">View Article</a>
        </div>
      </div>
      
      <div class="event-li article">
        <%= image_tag('press-11alive.jpg', class: 'img-responsive', alt: "Changing lives through clothes: Nonprofit supports women in need with free shopping sprees") %>
        <div class="textbox">
          <p class="pub">11alive</p>
          <h4>Changing lives through clothes: Nonprofit supports women in need with free shopping sprees</h4>
          <p class="desc">Free Fab'rik aims to change lives through clothes.</p>
          <a class="text-link" target="_blank" href="https://www.11alive.com/article/news/local/features/changing-lives-through-clothes-nonprofit-supports-women-in-need-with-free-shopping-sprees/85-592609812">View Article</a>
        </div>
      </div>
    </div>
	</div>
</div>