config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'account', to: 'devise/sessions#show'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'messages', to: 'static_pages#messages'
  get 'love-what-you-do', to: 'static_pages#love-what-you-do'
  get 'buy-the-book', to: 'static_pages#buy-the-book'
  get 'past-events', to: 'static_pages#past-events'
  get 'press', to: 'static_pages#press'
  get 'heart', to: 'static_pages#heart'
  get 'press-form', to: 'static_pages#press-form'

  get '/fabrik_book', to: 'links#fabrik_book'
  get '/amazon_book', to: 'links#amazon_book'
  get '/fb', to: 'links#fb'
  get '/insta', to: 'links#insta'
  get '/asher', to: 'links#asher'
  get '/ff', to: 'links#ff'
  get '/fab', to: 'links#fab'
  get '/twitter', to: 'links#twitter'


  # resources :articles do 
  #   member do
  #     delete :delete_image_attachment
  #   end
  # end
  # get 'press', to: 'articles#index', as: 'press'

  # resources :archives do 
  #   member do
  #     delete :delete_image_attachment
  #   end
  # end
  # get 'past-events', to: 'archives#index', as: 'past-events'

  resources :requests, :except => [:new]
  get '/speaking', to: 'requests#new', as: 'speaking'
  post '/speaking', to: 'requests#create'

  resources :features, :except => [:new]
  get '/feature-dana', to: 'features#new', as: 'feature-dana'
  post '/feature-dana', to: 'features#create'

  resources :events do 
    member do
      delete :delete_image_attachment
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  # validates :event_type, presence: true
  validates :title, presence: true
  validates :date, presence: true
  validates :time, presence: true
  validates :location, presence: true
  validates :description, presence: true
  # validates :price, presence: true
  # validates :link, presence: true
  # validates :image, presence: true
  # validates :extras, presence: true

  has_one_attached :image
  # default_scope -> { order(date: :desc) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :show, :update, :destroy, :delete_image_attachment]

  def index
    @events = Event.all
  end

  def delete_image_attachment
    @event.image.purge
    redirect_back(fallback_location: request.referer)
  end

	def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
	    redirect_to events_path, notice: "Your event has been created."
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to events_path
    else
      render 'edit'
    end
  end

  def show 
  end

  def edit
  end

  def destroy
    @event.destroy

    redirect_to events_path
  end

  private
	  def set_event
			@event = Event.find(params[:id])
	  end

    def event_params
      params.require(:event).permit(:event_type, :title, :date, :time, :location, :description, :price, :link, :image, :extras, :honey)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= render 'shared/errors', obj: @event %>
  <%= form_for(@event, :html => {class: "form-horizontal admin-form", role: "form" }) do |f| %>
  <fieldset>
   <!--  < if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    < end %> -->

    <% if flash[:alert] %>
      <div class="notice"><%= flash[:alert] %></div>
    <% end %>

    <p class="print">* indicates required field</p>
    <div class="clearfix"></div><hr>

		<!-- <div class="form-group type">
		  <label>* Event Type:</label><br>
		  <= f.select(:event_type) do %>
		    < [['Speaking', 'Speaking'], ['Book tour', 'Book tour']].each do |c| -%>
		      <= content_tag(:option, c.first, value: c.last) %>
		    < end %>
		  < end %>
		</div> -->

		<div class="form-group title">
		  <label>* Event Title:</label><br>
		  <%= f.text_field :title %> 
		</div>

		<div class="form-group date">
		  <label>* Date:</label><br>
		  <%= f.date_field :date, value: f.object.date %>
		</div>

		<div class="form-group time">
		  <label>* Time:</label><br>
		  <%= f.text_field :time %> 
		</div>

		<div class="form-group location">
		  <label>* Location:</label><br>
		  <%= f.text_field :location %> 
		</div>

		<div class="form-group description">
		  <label>* Description:</label><br>
		  <%= f.text_area :description %> 
		</div>

		<div class="form-group price">
		  <label>Price:</label><br>
		  <%= f.text_field :price %> 
		</div>

		<div class="form-group link">
		  <label>Link:</label><br>
		  <%= f.text_field :link %> 
		</div>

		<div class="form-group image">
		  <label>Image:</label><br>
		  <div class="image-box">
			  <%= f.file_field :image %>

			  <% unless @event.new_record? %>
					<% if @event.image.attached? %>
						<div class="current">
							<p class="tsmall">Current Image:</p>
						  <div class="thumb"><%= image_tag @event.image %></div>
							<%= link_to '[ Remove image ]', delete_image_attachment_event_url(@event), class: 'rmv-img',
		                method: :delete,
		                data: { confirm: 'Are you sure you want to delete this image?' } %>
	          </div>
					<% end %>
				</div>
	    <% end %>
		</div>

		<div class="form-group extras">
		  <label>Extra Info:</label><br>
		  <%= f.text_area :extras %> 
		</div>

    <div class="form-group honey">
      <%= label_tag :honey %>
      <%= f.text_field :honey %>
      <span class="help">Do not fill in this field. It is an anti-spam measure.</span>
    </div>

    <div class="form-group submit">
      <%= f.submit "Submit", :class=> "send-message" %>
    </div>

		 <%= link_to "[ Cancel and Return ]", :back, class: 'text-link admin' %>
  </fieldset>
<% end %>

app/views/events/edit.html.erb
<% @page_title = "Edit Event" %>
<% @page_description = "" %>

<div class="ipage-header">
	<div class="inside">
	  <div class="title-left">
	    <h1><%= @page_title %></h1>
	  </div>
	</div>
</div>

<div class="full-sec">
	<div class="inside med">
    <%= render 'form' %>
	</div>
</div>

app/views/events/index.html.erb
<% @page_title = "Upcoming Events" %>
<% @page_description = "Take a look at Dana's upcoming speaking engagements, and find one near you." %>

<div class="event-lay">
	<!-- <div class="inside lg">
		<div class="ehead">
			<div class="inside">
				<h1><%= @page_title %></h1>
			</div>
		</div>
	</div> -->
	<div class="inside">
		<!-- COPIED HEADLINE FROM SPEAKING PAGE -->
		<div class="title">
			<h1>Get ready to get <span class="lspace">inspired.</span></h1>
			<% if user_signed_in? && current_user.admin? %>
				<%= link_to "Create New Event", new_event_path, class: 'ds-link admin' %>
			<% end %>
		</div>
	</div>

	<div class="event-list">
		<div class="inside med2-def">
			<!-- < if user_signed_in? && current_user.admin? %>
		    <button class="admin-uk wl-uk uk-float-right" type="button"><span  uk-icon="icon: settings;"></span></button>
		    <div uk-dropdown="mode: click; pos: bottom-right; boundary: .wl-uk;">
					<%= link_to "Create New Event", new_event_path, class: 'ds-link' %>
		    </div>
			< end %> -->

			<% @events.each do |event| %>
				<div class="event-fw event-<%= event.id %>">
					<% if event.image.attached? %>
					  <%= image_tag event.image, alt: "#{event.title}"%>
					<% end %>

					<div class="textbox">
						<h4><%= event.title %></h4>
						<p><%= event.date.to_date.strftime("%m-%d-%Y") %> &nbsp; | &nbsp; <%= event.time %></p>
					
						<p class="desc"><%= event.description.truncate(60) %></p>

						<% if event.link != '' %>
							<!-- <= link_to "Event Details", event_path(event), class: 'ds-link' %> -->
							<%= link_to "Event Details", "#{event.link}", class: 'ds-link', target: '_blank' %>

						<% else %>
							<div class="ds-link def">Details Coming Soon</div>
						<% end %>

						<% if user_signed_in? && current_user.admin? %>
							<div class="clearfix space"></div>
							<%= link_to "[ Edit Event Details]", edit_event_path(event), class: 'text-link admin' %>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/events/new.html.erb
<% @page_title = "Create a New Event" %>
<% @page_description = "" %>


<div class="full-sec">
	<div class="inside med2-def">
		<h1><%= @page_title %></h1>
		<%= render 'form' %>
	</div>
</div>

app/views/events/show.html.erb
<% @page_title = "Event" %>
<% @page_description = "" %>



<div class="full-sec">
	<div class="inside med">
		<h1 class="text-center"><%= @event.title %></h1>
		<% if user_signed_in? && current_user.admin? %>
	    <button class="admin-uk wl-uk uk-float-right" type="button"><span  uk-icon="icon: settings;"></span></button>
	    <div uk-dropdown="mode: click; pos: bottom-right; boundary: .wl-uk;">
				<%= link_to "Create New Event", new_event_path, class: 'ds-link' %>
				<%= link_to "Edit Event", edit_event_path, class: 'ds-link' %>
	    </div>
		<% end %>
		<hr>

		<% if @event.image.attached? %>
		  <%= image_tag @event.image, alt: "#{@event.title}", class: 'event-image' %>
		<% end %>

		<div class="event-box">
			<h3><%= @event.date %></h3>
			<h3><%= @event.time %></h3>
			<h4><%= @event.location %></h4>
			<p><%= @event.description %></p>
			<!-- <h3><= @event.price %></h3> -->
			<!-- <h3><= @event.link %></h3> -->
			<!-- <h3><= @event.extras %></h3> -->
		</div>
	</div>
</div>