config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'account', to: 'devise/sessions#show'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'messages', to: 'static_pages#messages'
  get 'love-what-you-do', to: 'static_pages#love-what-you-do'
  get 'buy-the-book', to: 'static_pages#buy-the-book'
  get 'past-events', to: 'static_pages#past-events'
  get 'press', to: 'static_pages#press'
  get 'heart', to: 'static_pages#heart'
  get 'press-form', to: 'static_pages#press-form'

  get '/fabrik_book', to: 'links#fabrik_book'
  get '/amazon_book', to: 'links#amazon_book'
  get '/fb', to: 'links#fb'
  get '/insta', to: 'links#insta'
  get '/asher', to: 'links#asher'
  get '/ff', to: 'links#ff'
  get '/fab', to: 'links#fab'
  get '/twitter', to: 'links#twitter'


  # resources :articles do 
  #   member do
  #     delete :delete_image_attachment
  #   end
  # end
  # get 'press', to: 'articles#index', as: 'press'

  # resources :archives do 
  #   member do
  #     delete :delete_image_attachment
  #   end
  # end
  # get 'past-events', to: 'archives#index', as: 'past-events'

  resources :requests, :except => [:new]
  get '/speaking', to: 'requests#new', as: 'speaking'
  post '/speaking', to: 'requests#create'

  resources :features, :except => [:new]
  get '/feature-dana', to: 'features#new', as: 'feature-dana'
  post '/feature-dana', to: 'features#create'

  resources :events do 
    member do
      delete :delete_image_attachment
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="top-foot">
		<div class="inside">
			<div class="border-row"></div>
		</div>
			
		<div class="insideX medDef">
			<!-- <div class="ftBlock one">
				<h4>Speaking.</h4>
				<ul>
					<li><%= link_to "Event Request", speaking_path %></li>
					<li><%= link_to "Past Events", past_events_path %></li>
					<li><%= link_to "Messages", messages_path %></li>
				</ul>
			</div> -->

			<div class="ftBlock two">
				<h4>Book.</h4>
				<ul>
					<li><%= link_to "About the Book", love_what_you_do_path %></li>
					<li><%= link_to "Buy the Book", 'https://fabrikstyle.com/products/love-what-you-do', target: '_blank' %></li>
				</ul>
			</div>

			<div class="clearfix mobile"></div>

			<div class="ftBlock three">
				<h4>About.</h4>
				<ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <!-- <li><%= link_to "Press", press_path %></li> -->
          <!-- <li><%= link_to "Feature Dana", feature_dana_path %></li> -->
				</ul>
			</div>

			<div class="ftBlock four">
				<h4>Heart.</h4>
				<ul>
					<li class="fab"><%= link_to(image_tag('fabrik.png', alt: "fab'rik logo", class: 'nav-fab'), '/fab', target: '_blank') %></li>
					<li><%= link_to "free fab'rik", '/ff', target: '_blank', class: 'norm' %></li>
					<li><%= link_to "Asher", '/asher', target: '_blank' %></li>
				</ul>
			</div>

			<div class="clearfix mob"></div>
			<div class="ftBlock soc">
				<h4>Subscribe.</h4>
				<ul class="social"><%= render 'shared/social' %></ul>
				<div class="clearfix"></div>
				<p>Receive inspo, access to insider perks, and more. </p>

				<!-- Begin Mailchimp Signup Form -->
				<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
				<div id="mc_embed_signup">
					<form action="https://fabrikstyle.us9.list-manage.com/subscribe/post?u=7ee7573a2bfbcb20728257207&amp;id=b26eebfc72" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
				    <div id="mc_embed_signup_scroll">
							<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="EMAIL" required>
					    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_7ee7573a2bfbcb20728257207_b26eebfc72" tabindex="-1" value=""></div>
				    	<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
				    </div>
					</form>
				</div>
				<!--End mc_embed_signup-->
			</div>
		</div>
	</div>

	<div class="btm-foot">
		<div class="inside xl">
			<div class="copy"><p>Copyright <%= Time.now.year %> Dana Spinola. All rights reserved. </p></div>
			<div class="hs"><p>Design by <%= link_to "High Seas Design House.", 'https://hsdesignhouse.com', target: '_blank' %> </p></div>
		</div>
	</div>
  <a href="#" class="scroll-up"></a>
</footer>

app/views/layouts/_header.html.erb
<% if user_signed_in? && current_user.admin? %>
  <div class="account-bar">
    <div class="account"><%= link_to "Admin *", account_path %></div>
  </div>
<% end %>

<div class="mobile-above">
  <div class="inside">
    <div class="nb-logo mobile">
      <%= link_to(image_tag('ds-logo.png', class: 'img-responsive', alt: 'Dana Spinola Logo for mobile'), root_path, class: 'logo-name') %>
    </div>

    <div class="mobile-nav">
      <button class="uk-button" type="button" uk-toggle="target: #offcanvas-nav">
        <span class="mmenu" uk-icon="icon: menu; ratio: 1.5;"></span>
      </button>
      <%= render 'layouts/mobile-nav' %>
    </div>
  </div>
</div>

<header class="inline-header centered">
<!-- <header class="inline-header centered" uk-sticky="sel-target: .inline-header; cls-active: uk-navbar-sticky"> -->
  <nav class="uk-navbar-container uk-navbar-transparent" uk-navbar>
    <div class="navbar-center">
      <div class="nb-logo">
        <%= link_to(image_tag('ds-logo.png', class: 'img-responsive', alt: 'Dana Spinola Logo'), root_path, class: 'logo-name') %>
      </div>

      <div class="navstick">
        <ul class="uk-navbar-nav">
          <li class="<% if current_page?('/about') %>active<% end %>"><%= link_to "About", about_path %></li>
          <!-- <li><%= link_to "Events", events_path %></li> -->

          <!-- <li class="<% if current_page?('/speaking') || current_page?('/past-events') || current_page?('/messages') %>active<% end %>">
            <%= link_to "Speaking", speaking_path %>
            <div class="uk-navbar-dropdown">
              <ul class="uk-nav uk-navbar-dropdown-nav">
                <li><%= link_to "Past Events", past_events_path %></li>
                <li><%= link_to "Messages", messages_path %></li>
                <li><%= link_to "Event Request", speaking_path %></li>
              </ul>
            </div>
          </li> -->

          <li class="<% if current_page?('/love-what-you-do') %>active<% end %>"><%= link_to "Book", love_what_you_do_path %></li>
          
          <!-- <li class="<% if current_page?('/press') || current_page?('/feature-dana') %>active<% end %>"><%= link_to "Press", press_path %>
            <div class="uk-navbar-dropdown">
              <ul class="uk-nav uk-navbar-dropdown-nav">
                <li><%= link_to "Feature Dana", feature_dana_path %></li>
              </ul>
            </div>
          </li> -->

          <li class="<% if current_page?('/heart') %>active<% end %>"><%= link_to "Heart", heart_path %></li>
           
          <li class="fab"><%= link_to(image_tag('fabrik.png', alt: "fab'rik logo", class: 'nav-fab'), '/fab', target: '_blank') %></li>
        </ul>
      </div>

    </div>
  </nav>
</header>

<% unless current_page?(root_path) %>
<%= render 'shared/collage-hd' %>
<% end %>

app/views/layouts/_mobile-nav.html.erb
<div id="offcanvas-nav" uk-offcanvas="overlay: true; flip: true">
  <div class="uk-offcanvas-bar mobile mnav">
    <button class="uk-offcanvas-close uk-dark" type="button" uk-close></button>
    <ul class="uk-nav nav-default">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>

      <!-- <li class="uk-nav-header">Speaking</li> -->
      <!-- <li><%= link_to "Speaking", speaking_path %></li>
      <li><%= link_to "Past Events", past_events_path %></li>
      <li><%= link_to "Messages", messages_path %></li> -->

      <li><%= link_to "Book", love_what_you_do_path %></li>
      
      <!-- <li><%= link_to "Press", press_path %></li>
      <li><%= link_to "Feature Dana", feature_dana_path %></li> -->
      
      <li><%= link_to "Heart", heart_path %></li>
      <li class="fab"><%= link_to(image_tag('fabrik-white.png', alt: "fab'rik logo", class: 'nav-fab'), '/fab', target: '_blank') %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    
    <title><%= @page_title  %> | Dana Spinola</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.3/css/uikit.min.css" />
    <meta name="description" content= "<%= @page_description %>">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- <= render 'layouts/rails-default' %> -->
    <!-- <= render 'layouts/shim' %> -->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-135627355-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-135627355-1');
    </script>

    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.3/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.3/js/uikit-icons.min.js"></script>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/header' %>
    <p class="notice reg"><%= notice %></p>
    <p class="alert reg"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>